apiVersion: v1
kind: Deployment
metadata:
  name: register-service-deployment
spec:
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: register-service
    spec:
      containers:
      - name: register-service
        image: blusky10/mail-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080