apiVersion: v1
kind: ReplicationController
metadata:
  name: register-rc
spec:
  replicas: 2
  selector:
    app: register-app
  template:
    metadata:
      name: register-node
      labels:
        app: register-app
    spec:
      containers:
      - name: register-app
        image: asia.gcr.io/coral-shoreline-209014/register-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080