apiVersion: v1
kind: Deployment
metadata:
  name: register-service-deployment
spec:
  replicas: 2
  minReadySeconds: 5
  selector:
    matchLabels:
        app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
      - name: register-app
        image: asia.gcr.io/coral-shoreline-209014/register-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: register.service.url
          valueFrom:
            configMapKeyRef:
              name: register-config-map
              key: REGISTER_SERVICE_URL
        - name: mail.service.url
          valueFrom:
            configMapKeyRef:
              name: register-config-map
              key: MAIL_SERVICE_URL