apiVersion: v1
kind: ReplicationController
metadata:
  name: mail-rc
spec:
  replicas: 2
  selector:
    app: mail-app
  template:
    metadata:
      name: mail-node-pod
      labels:
        app: mail-app
    spec:
      containers:
      - name: mail-app
        image: asia.gcr.io/coral-shoreline-209014/mail-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080